### ISSUE TITLE
need to read container time at startup

### ISSUE THREAD

**Issue by robnagler** [radiasoft/rsdockerspawner#28]
When the server starts, need to set start_time from container start time. Otherwise, min activity is reset at startup, which means a user added to the allow list is not allowed to join until the min activity times out. Also, this means long running containers always have the same start time, which ends up being random on what gets garbage collected.

Relates to #14. Peruse all containers on each machine, and remove those that don't belong (not in the right pool) or are not running. Also related to #18.

**Comment by e-carlin** [comment]
@robnagler I'm a little confused by what you say and what I see in the code.

From my understanding of the code min activity is going to be reset at startup no matter what. [`__init_class`](https://github.com/radiasoft/rsdockerspawner/blob/fd6dcf84ad9848419c52ff3de8951918b9ce3fc4/rsdockerspawner/rsdockerspawner.py#L527) ultimately calls [`__slot_assign`](https://github.com/radiasoft/rsdockerspawner/blob/fd6dcf84ad9848419c52ff3de8951918b9ce3fc4/rsdockerspawner/rsdockerspawner.py#L594) for each running container. This will reset the `start_time` for all existing containers. `min_activity` (`slot.activity_secs` to be specific) will be [reset regardless](https://github.com/radiasoft/rsdockerspawner/blob/fd6dcf84ad9848419c52ff3de8951918b9ce3fc4/rsdockerspawner/rsdockerspawner.py#L531). This reset was added to [avoid a race condition in garbage collection](https://github.com/radiasoft/rsdockerspawner/commit/38474778c8c14cc4d40f50a3fc4f394a240bcefe#diff-a9e82fda86e08a6c08038f6b9322e8e2d78662004aca4fe0f6763f73e6bea228R400). I believe the race condition is that a slot could be gc'ed while we are still assigning it and you could end up with a gc'ed slot assigned to a container. 

So we are going to need to do two things:
1. Use a flag in `__slot_assign` to not reset activity_secs and start_time during the initialization process
2. Use a flag/lock to ensure that a slot isn't gc'ed while reconnecting a container to it instead of setting [`activity_secs`](https://github.com/radiasoft/rsdockerspawner/blob/fd6dcf84ad9848419c52ff3de8951918b9ce3fc4/rsdockerspawner/rsdockerspawner.py#L531) to now. 

I'm going to start implementing but if something sounds wrong lmk.

**Comment by robnagler** [comment]
There are two calls to `__slot_assign()`. In the case of server startup, it could be supplied the values that are collected from the container or by reading the existing rsdockerspanwer.json. There is no race condition here, since the container is already allocated.
